server:
  port: 8888

# thymeleaf 配置
spring:
  thymeleaf:
    suffix: .html
    encoding: utf-8
    mode: HTML5
    cache: false
    prefix: classpath:/templates
    servlet:
      content-type: text/html
  # mysql 配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: yumuing
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  # 邮箱配置：mailProperties
  mail:
    host: smtp.qq.com
    username: 1942588530@qq.com
    # 授权码
    password: wybqbwgfnfawddab
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: false
          debug: true

# mybatis-plus 配置

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: top.yumuing.community.entity

# Logger 配置：slf4j
#logging:
#  level.top.yumuing.community: info
#  file:
#    name: logs/community.log
logging:
  config: classpath:logback-spring.xml


